using System.Data;
using Oracle.ManagedDataAccess.Client;

/// <summary>
/// Classe de reposit�rio para gerenciar entidades Aluno no banco de dados.
/// </summary>
public class AlunoRepository : IRepository<Aluno>
{
    /// <summary>
    /// Obt�m ou define a string de conex�o com o banco de dados.
    /// </summary>
    public string ConnectionString { get; set; }

    /// <summary>
    /// Inicializa uma nova inst�ncia da classe <see cref="AlunoRepository"/>.
    /// </summary>
    /// <param name="connectionString">A string de conex�o com o banco de dados.</param>
    public AlunoRepository(string connectionString)
    {
        ConnectionString = connectionString;
    }

    /// <summary>
    /// Garante que o esquema do banco de dados para a tabela Aluno exista.
    /// </summary>
    public void GarantirEsquema()
    {
        const string verificaTabela = @"
        SELECT COUNT(*)
        FROM USER_TABLES
        WHERE TABLE_NAME = 'ALUNOS'";

        const string ddl = @"
        CREATE TABLE Alunos (
            Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            Nome VARCHAR2(100) NOT NULL,
            Idade NUMBER(3) NOT NULL,
            Email VARCHAR2(100) NOT NULL,
            DataNascimento DATE NOT NULL
        )";

        using var conn = new OracleConnection(ConnectionString);
        conn.Open();
        using var checkCmd = new OracleCommand(verificaTabela, conn);
        var existe = Convert.ToInt32(checkCmd.ExecuteScalar()) > 0;

        if (!existe)
        {
            using var createCmd = new OracleCommand(ddl, conn);
            createCmd.ExecuteNonQuery();
        }
    }

    /// <summary>
    /// Insere um novo registro de Aluno no banco de dados.
    /// </summary>
    /// <param name="nome">O nome do Aluno.</param>
    /// <param name="idade">A idade do Aluno.</param>
    /// <param name="email">O email do Aluno.</param>
    /// <param name="dataNascimento">A data de nascimento do Aluno.</param>
    /// <returns>O ID do Aluno rec�m-inserido.</returns>
    public int Inserir(string nome, int idade, string email, DateTime dataNascimento)
    {
        string sql = @"
            INSERT INTO Alunos (Nome, Idade, Email, DataNascimento)
            VALUES (:nome, :idade, :email, TO_DATE(:dataNascimento, 'yyyy-MM-dd'))
            RETURNING Id INTO :id";

        using (var conn = new OracleConnection(ConnectionString))
        {
            OracleCommand cmd = new OracleCommand(sql, conn);
            cmd.Parameters.Add(new OracleParameter("nome", nome));
            cmd.Parameters.Add(new OracleParameter("idade", idade));
            cmd.Parameters.Add(new OracleParameter("email", email));
            cmd.Parameters.Add(new OracleParameter("dataNascimento", dataNascimento.ToString("yyyy-MM-dd")));

            OracleParameter idParam = new OracleParameter("Id", OracleDbType.Int32);
            idParam.Direction = ParameterDirection.Output;
            cmd.Parameters.Add(idParam);
            conn.Open();
            cmd.ExecuteNonQuery();
            
            return Convert.ToInt32(idParam.Value.ToString());
        }
    }

    /// <summary>
    /// Recupera uma lista de todos os registros de Aluno do banco de dados.
    /// </summary>
    /// <returns>Uma lista de entidades Aluno.</returns>
    public List<Aluno> Listar()
    {
        throw new NotImplementedException();
    }

    /// <summary>
    /// Atualiza os dados de um registro de Aluno no banco de dados.
    /// </summary>
    /// <param name="id">O ID do Aluno a ser atualizado.</param>
    /// <param name="nome">O novo nome do Aluno.</param>
    /// <param name="idade">A nova idade do Aluno.</param>
    /// <param name="email">O novo email do Aluno.</param>
    /// <param name="dataNascimento">A nova data de nascimento do Aluno.</param>
    /// <returns>O n�mero de linhas afetadas.</returns>
    public int Atualizar(int id, string nome, int idade, string email, DateTime dataNascimento)
    {
        throw new NotImplementedException();
    }

    /// <summary>
    /// Exclui um registro de Aluno do banco de dados.
    /// </summary>
    /// <param name="id">O ID do Aluno a ser exclu�do.</param>
    /// <returns>O n�mero de linhas afetadas.</returns>
    public int Excluir(int id)
    {
        throw new NotImplementedException();
    }

    /// <summary>
    /// Busca registros de Aluno no banco de dados com base em um termo e valor.
    /// </summary>
    /// <param name="propriedade">A propriedade a ser pesquisada (coluna).</param>
    /// <param name="valor">O valor a ser pesquisado.</param>
    /// <returns>Uma lista de entidades Aluno correspondentes.</returns>
    public List<Aluno> Buscar(string propriedade, object valor)
    {
        throw new NotImplementedException();
    }
}
